---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Lua脚本启动ABFW框架爱，加载指定包中的资源
--- Created by 74144.
--- DateTime: 2019/8/25 17:58
---

--定义局部变量
local loc_SceneName = nil         --场景名称
local loc_PackageName = nil       --AB包名称
local loc_AssetName = nil         --资源名称

--导入Xlua Package
local util = require("xlua.util")       --异步转同步函数

--实例化ABFW框架中核心管理类
local AbMgrClass = CS.ABFW.AssetBundleMgr
local AbMgrObject = AbMgrClass.GetInstance

--加载AB包（通过调用ABFW框架）
local function LoadABPackage(SceneName, packageName, assetName)
    --todo
    loc_SceneName = SceneName
    loc_PackageName = packageName
    loc_AssetName = assetName
    AbMgrObject:LoadAssetBundlePackage(loc_SceneName, loc_PackageName, FinishWork)
end

--(回调方法）加载指定的AB包中内部的资源
local function FinishWork()
    --资源对象
    local assetObj

    --调用AB包中的资源
    assetObj = AbMgrObject:LoadAsset(loc_SceneName, loc_PackageName, loc_AssetName, false)

    if (assetObj ~=nil) then
        CS.UnityEngine.Object.Instantiate(assetObj)
        print("CorLaunchABFW.lua/FinishWork function / 加载指定资源包成功 ")
    else
        print("CorLaunchABFW.lua/FinishWork function / 加载对象为nil，请检查 ")
    end
end

return{
    yield_return = util.async_to_sync(LoadABPackage)
}