---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- 启动ABFW框架
--- 通过调用ABFW 核心API，实现lua中加载unity中的资源（预设 ）
--- Created by 74144.
--- DateTime: 2019/8/26 3:30
---

--调用UI预设核心参数
local sceneName ="xxx"      --场景名称
local packageName="xxx"     --ab包名称
local assetName="xxx"       --资源名称

LauchABFW ={}
local this= LauchABFW

--引用异步转同步，加载ABFW框架功能
local yield =require("CorLaunchABFW").yield_return

--Lua的协同
local co=coroutine.create(
        function()
             yield(sceneName,packageName,assetName)
        end
)

--启动lua的协同
function LauchABFW:StartABFW()
    assert(coroutine.resume((co)))
end